import Chess
a = Chess.Pieces()
print a.details()
print a.moves()
a = Chess.Pieces(1,'b')
print a.details()
print a.moves()
a = Chess.Pieces(1,'n')
print a.details()
print a.moves()
a = Chess.Pieces(1,'r')
print a.details()
print a.moves()

print type(a.move[0])==int

a = Chess.Pieces(1, 'b', [3,3])
print a.checkMoves()
a = Chess.Pieces(1, 'b', [3,6])
print a.checkMoves()
a = Chess.Pieces(1, 'n', [2,1])
print a.checkMoves()
a = Chess.Pieces(1, 'n', [3,6])
print a.checkMoves()
a = Chess.Pieces(1, 'r', [3,0])
print a.checkMoves()
a = Chess.Pieces(1, 'r', [3,6])
print a.checkMoves()
a = Chess.Pieces(1, 'r', [6,6])
print a.checkMoves()
